on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read
      checks: write
      statuses: write

    strategy:
      fail-fast: false # run tests even if lint/fmt fails
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        task:
          - { name: 'Formatting', command: 'pnpm run fmt:check' }
          - { name: 'Linting', command: 'pnpm run lint --format=github' }
          - { name: 'Testing', command: 'pnpm run test:ci' }

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm ci

      - name: Run Task Command
        run: ${{ matrix.task.command }}

      - name: Report tests
        if: matrix.task.name == 'Testing' && always()
        uses: im-open/process-jest-test-results@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: ./jest-results.json
          report-name: Test Results
          comment-identifier: '${{ matrix.node-version }}-failures'

      - name: Report Coverage
        if: matrix.task.name == 'Testing' && always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: ./coverage/coverage-summary.json
